# Generated by Django 5.2.10 on 2026-02-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='address',
            field=models.CharField(max_length=200, unique=True, verbose_name='Адрес'),
        ),
    ]
