# Generated by Django 5.2.10 on 2026-02-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_coordinates_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Долгота'),
        ),
    ]
