# Generated by Django 5.2.10 on 2026-02-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_closed',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Необработан'), ('in_progress', 'Обработан'), ('completed', 'Завершён')], default='new', max_length=20),
        ),
    ]
