# Generated by Django 5.2.10 on 2026-02-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_called_at_order_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('none', 'Не выбран'), ('epay', 'Электронно'), ('cash', 'Наличностью')], default='none', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
