# Generated by Django 5.2.10 on 2026-02-09 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant_branch',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='foodcartapp.restaurant', verbose_name='Ресторан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Необработан'), ('in_progress', 'Обработан'), ('completed', 'Завершён')], db_index=True, default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
